[project]
name = "tests"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ansible<12.0.0",
    "labgrid>=25.0",
    "pytest>=8.4.1",
    "pytest-check>=2.5.3",
    "pytest-harvest>=1.10.5",
]

[tool.uv.sources]
labgrid = { git = "https://github.com/aparcar/labgrid.git", branch = "aparcar/staging" }

[dependency-groups]
dev = ["isort>=6.0.1", "ruff>=0.12.0"]

[tool.ruff]
line-length = 88
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "I", "W"]

[tool.ruff.lint.isort]
known-first-party = ["openwrt_scheduler", "labgrid_runner"]

[tool.isort]
profile = "black"
line_length = 88
known_first_party = ["openwrt_scheduler", "labgrid_runner"]
