#!/bin/bash
# =============================================================================
# OpenWrt KernelCI QEMU Runner Setup
# =============================================================================
#
# Sets up a local QEMU test runner that polls the KernelCI API for jobs,
# runs OpenWrt firmware tests in QEMU, and submits results.
#
# Prerequisites:
#   - Docker and Docker Compose
#   - A KernelCI API token (get one from the server admin)
#
# Usage:
#   ./setup-runner.sh --token <KCI_API_TOKEN>
#   ./setup-runner.sh                          # prompts for token
#
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

API_URL="${KCI_API_URL:-https://api.openwrt-kci.aparcar.org}"
TOKEN=""
LAB_NAME=""

# --- Parse arguments ---

usage() {
    echo "Usage: $0 [--token TOKEN] [--lab-name NAME] [--api-url URL]"
    echo ""
    echo "Options:"
    echo "  --token TOKEN      KernelCI API token (or set KCI_API_TOKEN env var)"
    echo "  --lab-name NAME    Lab identifier (default: qemu-\$(hostname))"
    echo "  --api-url URL      KernelCI API URL (default: $API_URL)"
    echo ""
    echo "Environment variables:"
    echo "  KCI_API_TOKEN      API token (alternative to --token)"
    echo "  KCI_API_URL        API URL (alternative to --api-url)"
    echo "  LAB_NAME           Lab name (alternative to --lab-name)"
    exit 1
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --token) TOKEN="$2"; shift 2 ;;
        --lab-name) LAB_NAME="$2"; shift 2 ;;
        --api-url) API_URL="$2"; shift 2 ;;
        --help|-h) usage ;;
        *) echo "Unknown option: $1"; usage ;;
    esac
done

# --- Check prerequisites ---

echo "Checking prerequisites..."

if ! command -v docker &>/dev/null; then
    echo "Error: docker is not installed"
    echo "Install: https://docs.docker.com/engine/install/"
    exit 1
fi

if ! docker compose version &>/dev/null; then
    echo "Error: docker compose is not available"
    echo "Install: https://docs.docker.com/compose/install/"
    exit 1
fi

if ! docker info &>/dev/null 2>&1; then
    echo "Error: docker daemon is not running or you don't have permission"
    echo "Try: sudo usermod -aG docker \$USER && newgrp docker"
    exit 1
fi

echo "  docker: $(docker --version | head -1)"
echo "  compose: $(docker compose version | head -1)"

# --- Get API token ---

TOKEN="${TOKEN:-${KCI_API_TOKEN:-}}"

if [[ -z "$TOKEN" ]]; then
    echo ""
    echo "Enter your KernelCI API token:"
    read -r -s TOKEN
    echo ""
fi

if [[ -z "$TOKEN" ]]; then
    echo "Error: API token is required"
    exit 1
fi

# Validate token
echo "Validating API token against $API_URL..."
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
    -H "Authorization: Bearer $TOKEN" \
    "$API_URL/latest/nodes?limit=1" 2>/dev/null || echo "000")

if [[ "$HTTP_CODE" != "200" ]]; then
    echo "Error: API returned HTTP $HTTP_CODE — check your token and API URL"
    exit 1
fi
echo "  Token is valid."

# --- Set lab name ---

LAB_NAME="${LAB_NAME:-${LAB_NAME:-qemu-$(hostname -s 2>/dev/null || echo local)}}"
echo "  Lab name: $LAB_NAME"

# --- Generate .env ---

echo ""
echo "Writing .env file..."

cat > .env <<EOF
# Generated by setup-runner.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
KCI_API_URL=$API_URL
KCI_API_TOKEN=$TOKEN
LAB_NAME=$LAB_NAME
MAX_CONCURRENT_JOBS=1
POLL_INTERVAL=30
LOG_LEVEL=INFO
EOF

echo "  .env written"

# --- Build and start ---

echo ""
echo "Building containers (this may take a few minutes on first run)..."
docker compose build --quiet

echo "Starting coordinator and adapter..."
docker compose up -d

# --- Wait for coordinator health ---

echo "Waiting for labgrid coordinator..."
for i in $(seq 1 30); do
    if docker compose exec -T coordinator labgrid-client places &>/dev/null 2>&1; then
        echo "  Coordinator is ready."
        break
    fi
    if [[ $i -eq 30 ]]; then
        echo "Error: coordinator did not become healthy"
        docker compose logs coordinator
        exit 1
    fi
    sleep 2
done

# --- Create QEMU place ---

echo "Creating qemu_x86-64 place on coordinator..."

# Create the place (ignore error if it already exists)
docker compose exec -T adapter \
    labgrid-client -x coordinator:20408 create qemu_x86-64 2>/dev/null || true

# Set device_type tag so the adapter's discovery finds it
docker compose exec -T adapter \
    labgrid-client -x coordinator:20408 set-tags qemu_x86-64 device_type=qemu_x86-64

# Add a match so any resource can bind to this place
docker compose exec -T adapter \
    labgrid-client -x coordinator:20408 add-match qemu_x86-64 "*/*" 2>/dev/null || true

echo "  Place created."

# --- Verify ---

echo ""
echo "Verifying setup..."
echo "  Places on coordinator:"
docker compose exec -T adapter labgrid-client -x coordinator:20408 places 2>/dev/null | sed 's/^/    /'

echo ""
echo "=== Setup complete ==="
echo ""
echo "The runner is now polling $API_URL for qemu_x86-64 jobs."
echo ""
echo "Useful commands:"
echo "  docker compose logs -f adapter     # watch runner logs"
echo "  docker compose logs -f coordinator # watch coordinator logs"
echo "  docker compose ps                  # check container status"
echo "  docker compose down                # stop the runner"
echo "  docker compose up -d               # restart the runner"
echo ""
