- hosts: coordinator
  become: true
  vars:
    labnet: "{{ lookup('file', '../labnet.yaml') | from_yaml }}"
  tasks:
    - name: Create a user account called labgrid-dev
      user:
        name: labgrid-dev
        state: present

    - name: Add SSH keys to labgrid-dev from GitHub
      authorized_key:
        user: labgrid-dev
        state: present
        key: "{{ lookup('url', 'https://github.com/' + item + '.keys', split_lines=false) }}"
        comment: "{{ item }}"
      loop: "{{ ((labnet.labs.values() | map(attribute='maintainers') | flatten | list) + (labnet.labs.values() | map(attribute='access') | flatten | list)) | unique | list }}"

    - name: Add public SSH key of CI runner
      authorized_key:
        user: labgrid-dev
        state: present
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP0ZVlD9TmfAXL53Vq7V9WKE3KPomOa1jINyflrPWAlJ"
        comment: "labgrid-dev"

    - name: Add labs to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ hostvars[item].wireguard_ip }} {{ item }}"
        state: present
      loop: "{{ groups['labs'] }}"

    - name: Create .ssh directory
      file:
        path: /home/labgrid-dev/.ssh
        state: directory
        mode: "0700"

    - name: Add .ssh/config for labgrid-dev
      blockinfile:
        path: /home/labgrid-dev/.ssh/config
        block: |
          Host {{ item }}
            HostName {{ hostvars[item].wireguard_ip }}
            User labgrid-dev
        state: present
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
        create: true
      loop: "{{ groups['labs'] }}"

    - name: Add .ssh/config for {{ ansible_ssh_user }}
      blockinfile:
        path: /home/{{ ansible_ssh_user }}/.ssh/config
        block: |
          Host {{ item }}
            HostName {{ hostvars[item].wireguard_ip }}
            User labgrid-dev
        state: present
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
        create: true
      loop: "{{ groups['labs'] }}"

    - name: Install required packages
      apt:
        name:
          - nmap
        state: present
        update_cache: yes
