#!/bin/sh /etc/rc.common

START=90
STOP=10
USE_PROCD=1

start_service() {
	procd_open_instance
	# only reachable via SSH (LG_PROXY), like on the Debian hosts
	procd_set_param command /usr/bin/labgrid-coordinator --listen 127.0.0.1:20408
	procd_set_param env PYTHONUNBUFFERED=1 HOME=/home/labgrid-dev
	procd_set_param user labgrid-dev
	procd_set_param group labgrid-dev
	# places.yaml and resources.yaml are read from and written to the cwd
	procd_set_param cwd /etc/labgrid
	procd_set_param respawn 3600 5 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
