name: Pull Requests

on:
  pull_request:

env:
  PYTHONUNBUFFERED: "1"
  PYTEST_ADDOPTS: "--color=yes"
  LG_CONSOLE: "internal"
  RELEASE: "24.10.2"

concurrency:
  group: pr-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-qemu:
    name: QEMU ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: malta-be
            firmware: openwrt-${RELEASE}-malta-be-vmlinux-initramfs.elf
            dependency: qemu-system-mips

          - target: x86-64
            firmware: openwrt-${RELEASE}-x86-64-generic-squashfs-combined.img.gz
            dependency: qemu-system-x86

          - target: armsr-armv8
            firmware: openwrt-${RELEASE}-armsr-armv8-generic-initramfs-kernel.bin
            dependency: qemu-system-aarch64

    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get -y install \
            nmap \
            ${{ matrix.dependency }}

          # workaround until ARMSR is fixed
          if [ "${{ matrix.target }}" = "armsr-armv8" ]; then
            export RELEASE=23.05.5
            echo "RELEASE=${RELEASE}" >> $GITHUB_ENV
          fi

          echo "LG_ENV=targets/qemu_${{ matrix.target }}.yaml" >> $GITHUB_ENV
          echo "UPSTREAM_URL=https://mirror-03.infra.openwrt.org/releases/${RELEASE}/targets" >> $GITHUB_ENV

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Download test firmware
        env:
          target: ${{ matrix.target }}
        run: |
          wget $UPSTREAM_URL/${target/-/\/}/${{ matrix.firmware }} \
            --output-document ${{ matrix.firmware }}
          FIRMWARE_VERSION=$(curl $UPSTREAM_URL/${target/-/\/}/version.buildinfo)
          echo "FIRMWARE_VERSION=$FIRMWARE_VERSION" >> $GITHUB_ENV

      - name: Run test
        run: |
          gunzip ${{ matrix.firmware }} || true
          firmware=${{ matrix.firmware }}

          uv run pytest tests/ \
            --lg-log \
            --lg-colored-steps \
            --log-cli-level=CONSOLE \
            --firmware $GITHUB_WORKSPACE/${firmware/.gz/}

      - name: Upload console logs
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: console-${{ matrix.target }}
          path: console_*
